name: cookbookdeisy
description: "Flutter Cookbook App with interactive examples"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  flutter_staggered_grid_view: ^0.7.0
  animated_text_kit: ^4.2.2
  lottie: ^2.7.0
  shimmer: ^3.0.0
  url_launcher: ^6.2.1
  shared_preferences: ^2.2.0
  http: ^1.1.0
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true
  assets:
    - assets/lottie/